### ISSUE TITLE
Read JSON from #16 into shape objects for #1

### ISSUE THREAD

**Issue by mmoskowitz** [denismm/riklang#17]
Remaining:
- [x] getPointsForZigzag()
- [x] splitSpline()
- [x] getPointsForEllarc()
- [x] getPointsForSquiggle()
- [x] getPointsForFishBend()
- [x] getPointsForLobe()
- [x] generate pronominals in animate.js
- [x] review animation
- [x] - Four-T-Instrumentrec-1.Two-M-End-0
- [x] - Sound-T-Instrumentrec-1.Four-T-Patient-1

**Comment by mmoskowitz** [comment]
@denismm In the java version I used combinations of arcs and lines for this, and recategorized the various tentacleforms into 6 different shapes. But I'm more experienced now. What do you think about implementing this with splines? We could create a spline form for each tentacleform and then just interpolate the control points.

**Comment by denismm** [comment]
Excellent thought (and I've done the math for some of those already in rikchik.ps).  I think we'll need to have a few splines per glyph, both because of sharp-cornered strokes and because there's no single-spline circle.  Maybe they should all be 3 splines?

**Comment by denismm** [comment]
We decided on 4 splines per shape.  I did the math for spline-splitting in dmmlib.  Explanation in https://github.com/denismm/dmmlib/blob/master/lines/splitspline.txt

**Comment by mmoskowitz** [comment]
The math for elliptical arcs is... not simple. I saw one person saying that "halve the distance between x and y" was a good-enough approximation for the offset. I'm tempted to try it.

**Comment by denismm** [comment]
I'm not sure what you mean by the offset.  Don't you just calculate the regular arc and then scale the x and y components appropriately?

**Comment by denismm** [comment]
You found the appropriate lines in dmmlib/lines.ps?
	/theta adiff 2 div def
	/offset 1 theta cos sub theta sin div 0.75 div def

**Comment by mmoskowitz** [comment]
I had not. I will have to read that later when I'm not at work.

**Comment by mmoskowitz** [comment]
Four-T-Instrumentrec-1.Two-M-End-0 makes an animation issue clear: we're not basing the direction of ptweening in 180° situations on the previous segment.

**Comment by mmoskowitz** [comment]
Probably the ptweening for everything after the first leg should be based on the previous leg. Maybe convert the whole thing to a list of r and relative theta? Maybe at point generation time?

**Comment by denismm** [comment]
using relative theta would also remove the question of which way to go around, if you designate 180 as continuing straight.

**Comment by mmoskowitz** [comment]
Nice.

**Comment by denismm** [comment]
Um.  Noticed something when doodling and investigated it with a spreadsheet.

My calculation of "theta is 1/2 of A, offset is (1-cos(theta)/sin(theta)) * 4/3" is equivalent to "offset is 4/3 tan(A/4)".  Might be easier to deal with.

**Comment by mmoskowitz** [comment]
Useful. I read through /sparc on the train this morning and just shared that now.

**Comment by mmoskowitz** [comment]
Done. Integration work can happen in #1.
