### ISSUE TITLE
Corpus - Rikchik Language Institute posts

### ISSUE THREAD

**Issue by mmoskowitz** [denismm/riklang#28]
- [x] https://rikchiktalkhome.livejournal.com/1150.html
- [x] https://rikchiktalkhome.livejournal.com/1300.html
- [x] https://rikchiktalkhome.livejournal.com/1554.html
- [x] https://rikchiktalkhome.livejournal.com/2020.html
- [x] https://rikchiktalkhome.livejournal.com/2058.html
- [x] https://rikchiktalkhome.livejournal.com/2454.html
- [x] https://rikchiktalkhome.livejournal.com/2715.html
- [x] https://rikchiktalkhome.livejournal.com/2877.html
- [x] https://rikchiktalkhome.livejournal.com/3120.html
- [x] https://rikchiktalkhome.livejournal.com/3507.html
- [x] https://rikchiktalkhome.livejournal.com/3749.html
- [x] https://rikchiktalkhome.livejournal.com/3967.html
- [x] https://rikchiktalkhome.livejournal.com/409.html
- [x] https://rikchiktalkhome.livejournal.com/4160.html
- [x] https://rikchiktalkhome.livejournal.com/4411.html
- [x] https://rikchiktalkhome.livejournal.com/4717.html
- [x] https://rikchiktalkhome.livejournal.com/5099.html (Sonnet)
- [x] https://rikchiktalkhome.livejournal.com/5153.html
- [x] https://rikchiktalkhome.livejournal.com/5479.html
- [x] https://rikchiktalkhome.livejournal.com/5733.html
- [x] https://rikchiktalkhome.livejournal.com/6113.html
- [x] https://rikchiktalkhome.livejournal.com/6196.html
- [x] https://rikchiktalkhome.livejournal.com/6622.html
- [x] https://rikchiktalkhome.livejournal.com/6864.html
- [x] https://rikchiktalkhome.livejournal.com/6935.html
- [x] https://rikchiktalkhome.livejournal.com/7288.html
- [x] https://rikchiktalkhome.livejournal.com/757.html
- [x] https://rikchiktalkhome.livejournal.com/7667.html
- [x] https://rikchiktalkhome.livejournal.com/7689.html
- [x] https://rikchiktalkhome.livejournal.com/8115.html
- [x] https://rikchiktalkhome.livejournal.com/8304.html
- [x] https://rikchiktalkhome.livejournal.com/8641.html
- [x] https://rikchiktalkhome.livejournal.com/8705.html
- [x] https://rikchiktalkhome.livejournal.com/886.html
- [x] https://rikchiktalkhome.livejournal.com/8997.html
- [x] https://rikchiktalkhome.livejournal.com/9308.html
- [x] https://rikchiktalkhome.livejournal.com/9497.html

**Comment by mmoskowitz** [comment]
Trying to figure out how the sonnet should be broken up. By sentences? Not at all?

**Comment by denismm** [comment]
First thought was not at all but by sentence will be easier to connect en and rik meanings. Maybe entries per sentence plus a full entry?

**Comment by mmoskowitz** [comment]
They'll all be part of the same yaml file, so now I think just by sentence is the correct way. We should make sure that the display page for a sub-utterance (if such a thing exists) makes it easy to see the whole record.

**Comment by denismm** [comment]
I'll open an issue for that.

**Comment by denismm** [comment]
Whoa, nice
