### ISSUE TITLE
Create English->Rikchik dictionary, in ABC order

### ISSUE THREAD

**Issue by denismm** [denismm/riklang#3]
Include readings and definitions.

**Comment by mmoskowitz** [comment]
Here's my first pass at producing a sorted list. Better than this is likely to require adding gloss elements which is the next step.
[rikengdictwordlist.txt](https://github.com/denismm/riklang/files/1692371/rikengdictwordlist.txt)

**Comment by denismm** [comment]
Yeah, we'll probably need to go through and add glosses to everything.  Are we allowed multiple gloss entries?

**Comment by denismm** [comment]
Looks like gloss can have any number of texts inside.

**Comment by mmoskowitz** [comment]
@denismm Programming complete. Now just need to add html to engdict.xsl and integrate with rest of pages. And add a bunch of glosses.
